name: Install boilerplate

on: [push]

env:
  DOCKSAL_SSH_AGENT_USE_HOST: 0
  DOCKSAL_DNS_DISABLED: 1

jobs:
  install:
    name: Verify boilerplate installs
    runs-on: ubuntu-20.04
    steps:
      - name: Install Docksal
        run: curl -fsSL https://get.docksal.io | bash
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .docksal config
        run: |
          mkdir -p .docksal
          echo "config content here" > .docksal/docksal.yml
      - name: fin sysinfo
        run: fin sysinfo
      - name: Install boilerplate
        run: fin init
      - name: Test boilerplate
        run: fin test
      - name: fin config
        run: fin config
