name: Install boilerplate
on: [push]
env:
  DOCKSAL_SSH_AGENT_USE_HOST: 0
  DOCKSAL_DNS_DISABLED: 1

jobs:
  install:
    name: Verify boilerplate installs
    runs-on: ubuntu-20.04
    steps:
      - name: Install Docksal
        run: curl -fsSL https://get.docksal.io | bash
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Docksal configuration
        run: |
          mkdir -p .docksal/commands
          cat << EOF > .docksal/docksal.env
          DOCKSAL_STACK=default
          MYSQL_ROOT_PASSWORD=root
          MYSQL_DATABASE=drupal
          MYSQL_USER=drupal
          MYSQL_PASSWORD=drupal
          EOF
          echo "version: '2.1'
          services:
            cli:
              image: docksal/cli:php8.1-3.1
            db:
              image: docksal/db:1.1-mysql-5.7
          " > .docksal/docksal.yml
          cat << EOF > .docksal/commands/init
          #!/usr/bin/env bash
          fin project start
          fin composer install
          # Wait for MySQL to be ready
          fin exec cli 'while ! mysqladmin ping -h db --silent; do sleep 1; done'
          fin drush si -y --db-url=mysql://drupal:drupal@db/drupal
          EOF
          cat << EOF > .docksal/commands/test
          #!/usr/bin/env bash
          fin drush status
          EOF
          chmod +x .docksal/commands/init .docksal/commands/test
      - name: fin sysinfo
        run: fin sysinfo
      - name: Install boilerplate
        run: fin init
      - name: Check Drupal status
        run: fin drush status
      - name: fin config
        run: fin config